import crypto from 'node:crypto';
import { access, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { buildLocalGuideBaseline, splitLocalGuideMarkdown, validateRetiredLocalGuideBaseline, type LocalGuideBaselineEntry } from './generate-local-guide-baseline.ts';

type MigrationEntry = LocalGuideBaselineEntry & { markdownBody: string; sourceSha256: string };
type MigrationWarning = { slug: string; code: 'missing_image' | 'suspicious_image'; path: string };

export type LocalGuideMigrationArtifacts = {
  sql: string;
  report: {
    version: 1;
    baselineVersion: 1;
    entryCount: number;
    publishedCount: number;
    nonEmptyBodyCount: number;
    recommendedCount: number;
    categoryCounts: Record<string, number>;
    baselineSha256: string;
    payloadSha256: string;
    warnings: MigrationWarning[];
    entries: Array<{ slug: string; contentId: string; bodySha256: string; sourceSha256: string }>;
  };
};

const payloadDelimiter = '$local_guide_payload$';

function sha256(value: string): string { return crypto.createHash('sha256').update(value).digest('hex'); }

async function imageWarnings(siteRoot: string, entries: MigrationEntry[]): Promise<MigrationWarning[]> {
  const warnings: MigrationWarning[] = [];
  for (const entry of entries) {
    if (!entry.image) continue;
    if (!entry.image.startsWith('/')) {
      if (!entry.image.startsWith('https://')) warnings.push({ slug: entry.slug, code: 'suspicious_image', path: entry.image });
      continue;
    }
    await access(path.join(siteRoot, 'public', entry.image)).catch(() => {
      warnings.push({ slug: entry.slug, code: 'missing_image', path: entry.image! });
    });
  }
  return warnings;
}

export async function buildLocalGuideMigrationArtifacts(siteRoot = process.cwd()): Promise<LocalGuideMigrationArtifacts> {
  const baseline = await buildLocalGuideBaseline(siteRoot);
  const baselineJson = `${JSON.stringify(baseline, null, 2)}\n`;
  const committedBaseline = await readFile(path.join(siteRoot, 'src', 'data', 'local-guide-baseline.json'), 'utf8').catch(() => '');
  if (committedBaseline !== baselineJson) {
    throw new Error('Committed Local Guide baseline is stale. Regenerate and review it before generating the data migration.');
  }
  const entries: MigrationEntry[] = [];
  for (const entry of baseline.entries) {
    const source = await readFile(path.join(siteRoot, 'src', 'content', 'local-guide', entry.filename), 'utf8');
    const { body } = splitLocalGuideMarkdown(source, entry.filename);
    if (sha256(body) !== entry.bodySha256) throw new Error(`${entry.filename}: body no longer matches the committed baseline.`);
    const fingerprintInput = JSON.stringify({ ...entry, markdownBody: body });
    entries.push({ ...entry, markdownBody: body, sourceSha256: sha256(fingerprintInput) });
  }

  const payload = JSON.stringify(entries);
  if (payload.includes(payloadDelimiter)) throw new Error(`Migration content contains reserved delimiter ${payloadDelimiter}.`);
  const sql = `-- Generated by scripts/generate-local-guide-data-migration.ts. Do not edit manually.\n` +
`ALTER TABLE local_guide_entries\n` +
`  ADD COLUMN migration_source_sha256 TEXT\n` +
`    CHECK (migration_source_sha256 IS NULL OR migration_source_sha256 ~ '^[a-f0-9]{64}$');\n\n` +
`CREATE UNIQUE INDEX local_guide_entries_migration_source_idx\n` +
`  ON local_guide_entries (migration_source_sha256) WHERE migration_source_sha256 IS NOT NULL;\n\n` +
`DO $local_guide_migration$\n` +
`DECLARE\n  item JSONB;\n  entry_id BIGINT;\n  revision_id BIGINT;\nBEGIN\n` +
`  FOR item IN SELECT value FROM jsonb_array_elements(${payloadDelimiter}${payload}${payloadDelimiter}::jsonb)\n  LOOP\n` +
`    INSERT INTO local_guide_entries\n` +
`      (canonical_slug, legacy_content_id, legacy_id, status, migration_source_sha256)\n` +
`    VALUES (item->>'slug', item->>'contentId', item->>'legacyId', 'draft', item->>'sourceSha256')\n` +
`    RETURNING id INTO entry_id;\n\n` +
`    INSERT INTO local_guide_revisions\n` +
`      (local_guide_entry_id, revision_number, title, summary, markdown_body, category_id, category_label,\n` +
`       image_path, external_link, recommended, legacy_text, actor_type, source, action, change_summary)\n` +
`    VALUES (entry_id, 1, item->>'title', item->>'summary', item->>'markdownBody', item->>'category',\n` +
`      NULLIF(item->>'categoryLabel', ''), NULLIF(item->>'image', ''), NULLIF(item->>'externalLink', ''),\n` +
`      COALESCE((item->>'recommended')::boolean, FALSE), NULLIF(item->>'legacyText', ''),\n` +
`      'system', 'legacy_markdown_migration', 'imported',\n` +
`      jsonb_build_object('contentId', item->>'contentId', 'filename', item->>'filename',\n` +
`        'bodySha256', item->>'bodySha256', 'sourceSha256', item->>'sourceSha256'))\n` +
`    RETURNING id INTO revision_id;\n\n` +
`    UPDATE local_guide_entries SET status='published', working_revision_id=revision_id,\n` +
`      published_revision_id=revision_id, published_at=statement_timestamp(), updated_at=statement_timestamp()\n` +
`    WHERE id=entry_id;\n\n` +
`    INSERT INTO local_guide_events\n` +
`      (local_guide_entry_id, revision_number, actor_type, source, action, details)\n` +
`    VALUES (entry_id, 1, 'system', 'legacy_markdown_migration', 'created',\n` +
`      jsonb_build_object('contentId', item->>'contentId', 'sourceSha256', item->>'sourceSha256'));\n` +
`  END LOOP;\nEND;\n$local_guide_migration$;\n`;

  return {
    sql,
    report: {
      version: 1,
      baselineVersion: baseline.version,
      entryCount: entries.length,
      publishedCount: entries.length,
      nonEmptyBodyCount: entries.filter((entry) => entry.markdownBody.trim()).length,
      recommendedCount: entries.filter((entry) => entry.recommended).length,
      categoryCounts: baseline.categoryCounts,
      baselineSha256: sha256(baselineJson),
      payloadSha256: sha256(payload),
      warnings: await imageWarnings(siteRoot, entries),
      entries: entries.map(({ slug, contentId, bodySha256, sourceSha256 }) => ({ slug, contentId, bodySha256, sourceSha256 })),
    },
  };
}

async function main() {
  const siteRoot = process.cwd();
  const sqlPath = path.join(siteRoot, 'db', '034_local_guide_content_migration.sql');
  const reportPath = path.join(siteRoot, 'src', 'data', 'local-guide-migration-report.json');
  const sourceDirectory = path.join(siteRoot, 'src', 'content', 'local-guide');
  const sourceRetired = await access(sourceDirectory).then(() => false).catch((error: NodeJS.ErrnoException) => {
    if (error.code === 'ENOENT') return true;
    throw error;
  });
  if (process.argv.includes('--check') && sourceRetired) {
    const baselinePath = path.join(siteRoot, 'src', 'data', 'local-guide-baseline.json');
    const [baselineJson, existingSql, existingReport] = await Promise.all([
      readFile(baselinePath, 'utf8'), readFile(sqlPath, 'utf8'), readFile(reportPath, 'utf8'),
    ]);
    const baseline = validateRetiredLocalGuideBaseline(JSON.parse(baselineJson));
    const report = JSON.parse(existingReport) as LocalGuideMigrationArtifacts['report'];
    if (report.version !== 1 || report.baselineVersion !== baseline.version ||
        report.entryCount !== baseline.entryCount || report.publishedCount !== baseline.entryCount ||
        report.entries?.length !== baseline.entryCount || report.baselineSha256 !== sha256(baselineJson) ||
        new Set(report.entries?.map((entry) => entry.sourceSha256)).size !== baseline.entryCount ||
        !report.entries?.every((entry) => /^[a-f0-9]{64}$/.test(entry.sourceSha256)) ||
        !existingSql.includes('Generated by scripts/generate-local-guide-data-migration.ts') ||
        !existingSql.includes('INSERT INTO local_guide_entries')) {
      throw new Error('Retired Local Guide migration evidence is invalid or inconsistent.');
    }
    console.log(`Local Guide Markdown is retired; committed migration evidence is valid for ${report.entryCount} published entries.`);
    return;
  }
  const artifacts = await buildLocalGuideMigrationArtifacts(siteRoot);
  const report = `${JSON.stringify(artifacts.report, null, 2)}\n`;
  if (process.argv.includes('--check')) {
    const [existingSql, existingReport] = await Promise.all([
      readFile(sqlPath, 'utf8').catch(() => ''), readFile(reportPath, 'utf8').catch(() => ''),
    ]);
    if (existingSql !== artifacts.sql || existingReport !== report) {
      throw new Error('Local Guide data migration is stale. Run npm run generate:local-guide-migration.');
    }
    console.log(`Local Guide migration is current: ${artifacts.report.entryCount} published entries, ${artifacts.report.warnings.length} image warnings.`);
    return;
  }
  await Promise.all([writeFile(sqlPath, artifacts.sql, 'utf8'), writeFile(reportPath, report, 'utf8')]);
  console.log(`Generated ${artifacts.report.entryCount} entries with ${artifacts.report.warnings.length} image warnings.`);
}

if (import.meta.url === `file://${process.argv[1]}`) await main();
