import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  BOOKING_ACTIONS,
  BOOKING_STATUSES,
  BOOKING_TRANSITION_RULES,
  type BookingStatus,
} from '../src/lib/booking/lifecycle.ts';
import { validateBookingLifecycleModel } from '../src/lib/booking/lifecycle-integrity.ts';

const outputUrl = new URL('../../docs/booking-lifecycle.md', import.meta.url);
const escapeCell = (value: string): string => value.replaceAll('|', '\\|').replaceAll('\n', '<br>');
const titleCase = (value: string): string => value.replaceAll('_', ' ').replace(/\b\w/g, (character) => character.toUpperCase());

export function renderBookingLifecycleMarkdown(): string {
  const modelErrors = validateBookingLifecycleModel();
  if (modelErrors.length) throw new Error(`Cannot generate lifecycle documentation:\n- ${modelErrors.join('\n- ')}`);

  const statusRows = (Object.entries(BOOKING_STATUSES) as [BookingStatus, (typeof BOOKING_STATUSES)[BookingStatus]][])
    .map(([status, metadata]) => `| \`${status}\` | ${escapeCell(metadata.label)} | ${metadata.blocksDates ? 'Yes' : 'No'} | ${metadata.terminal ? 'Yes' : 'No'} | ${metadata.legacy ? 'Yes' : 'No'} | ${escapeCell(metadata.description)} |`)
    .join('\n');
  const actionRows = Object.entries(BOOKING_ACTIONS)
    .map(([action, metadata]) => `| \`${action}\` | ${escapeCell(metadata.label)} | ${escapeCell(metadata.description)} |`)
    .join('\n');
  const transitionRows = BOOKING_TRANSITION_RULES.map((rule) => {
    const requirements = rule.requirements.length ? rule.requirements.map(titleCase).join(', ') : 'None';
    const destination = rule.to === null ? '*Record deleted*' : `\`${rule.to}\``;
    return `| \`${rule.from}\` | \`${rule.action}\` | ${titleCase(rule.actor)} | ${destination} | ${titleCase(rule.calendarEffect)} | ${requirements} | \`${rule.activityEvent}\` |`;
  }).join('\n');

  return `# Canonical booking lifecycle\n\n> Generated by \`npm run generate:booking-lifecycle-docs\` from \`site/src/lib/booking/lifecycle.ts\`. Do not edit this file by hand.\n\n## Purpose\n\nThis document presents the executable rules used to decide whether a booking lifecycle action is allowed. The module is independent of Astro pages, SQL and email delivery so those layers can call one decision API instead of re-implementing policy. An unlisted decision fails closed.\n\n## Statuses\n\n| Status | Label | Blocks dates | Terminal | Legacy | Meaning |\n|---|---|---:|---:|---:|---|\n${statusRows}\n\n## Actions\n\n| Action | Label | Meaning |\n|---|---|---|\n${actionRows}\n\n## Allowed transitions\n\n| From | Action | Actor | To | Calendar effect | Requirements | Activity event |\n|---|---|---|---|---|---|---|\n${transitionRows}\n\n## Decision API\n\nUse \`decideBookingTransition({ status, action, actor })\` for an allowed/denied result, \`assertBookingTransitionAllowed(...)\` when denial must stop processing, and \`listAllowedBookingTransitions(status, actor)\` to discover available controls.\n\nThe decision module does not update the database. Processing code must lock the booking, ask the module for a decision, apply it conditionally against the expected source status, write the declared activity event and side effects, and commit atomically.\n\n## Required payment boundary\n\nA Booker payment declaration moves \`payment_pending\` to \`payment_reported\`. It does **not** confirm the booking. Only an administrator may verify the report and move \`payment_reported\` to \`confirmed\`.\n\n## Rule-change red/green cycle\n\n1. Run \`npm run generate:booking-lifecycle-docs\` and inspect this document.\n2. Run \`npm run check:booking-lifecycle-docs\` and \`npm run test:booking-lifecycle\`; both must pass.\n3. Express the intended policy change first in \`site/tests/booking-lifecycle/expected-transitions.ts\`.\n4. Run the tests and confirm the changed expectation causes a failure.\n5. Change \`site/src/lib/booking/lifecycle.ts\` to implement the decision.\n6. Run the tests until they pass.\n7. Regenerate this document and run the documentation check again.\n\nThe expected-transition fixture is intentionally separate from the executable model, allowing a test-first policy change to turn the suite red rather than testing the model against itself.\n`;
}

export async function generateBookingLifecycleDocs(options: { check?: boolean } = {}): Promise<void> {
  const expected = renderBookingLifecycleMarkdown();
  const outputPath = fileURLToPath(outputUrl);
  if (options.check) {
    let current = '';
    try { current = await readFile(outputPath, 'utf8'); }
    catch { throw new Error(`Generated lifecycle document is missing: ${outputPath}`); }
    if (current !== expected) throw new Error('Generated booking lifecycle documentation is out of date. Run npm run generate:booking-lifecycle-docs.');
    console.log(`Booking lifecycle documentation is current: ${outputPath}`);
    return;
  }
  await writeFile(outputPath, expected, 'utf8');
  console.log(`Generated booking lifecycle documentation: ${outputPath}`);
}

const invokedPath = process.argv[1] ? pathToFileURL(process.argv[1]).href : '';
if (invokedPath === import.meta.url) {
  generateBookingLifecycleDocs({ check: process.argv.includes('--check') }).catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
