import type pg from 'pg';import {getPool} from '../booking/db.ts';
export type OfferAllocation={arrangementName:string;approvedSleepingCapacity:number;alternativeSleepingNotes:string|null;explanatoryNotes:string|null;resources:Array<{key:string;name:string;sleepingCapacity:number;availabilityPropertyId:string|null}>};
const clean=(value:unknown,max:number)=>String(value??'').trim().slice(0,max);
export async function snapshotOfferAllocation(client:pg.PoolClient,input:{offerId:string;bundleId?:unknown;resourceKeys?:unknown[];arrangementName?:unknown;approvedSleepingCapacity?:unknown;alternativeSleepingNotes?:unknown;explanatoryNotes?:unknown;requiredAdults:number}){
 const bundleId=clean(input.bundleId,36);let resourceKeys=(input.resourceKeys??[]).map(value=>clean(value,100)).filter(Boolean);let arrangementName=clean(input.arrangementName,160);let bundleDbId:string|null=null;
 if(bundleId){const bundle=await client.query(`SELECT id,display_name FROM accommodation_bundles WHERE public_id=$1::uuid AND active=TRUE`,[bundleId]);if(!bundle.rowCount)throw new Error('INVALID_ALLOCATION_BUNDLE');bundleDbId=bundle.rows[0].id;arrangementName=arrangementName||bundle.rows[0].display_name;resourceKeys=(await client.query(`SELECT r.stable_key FROM accommodation_bundle_resources br JOIN accommodation_resources r ON r.id=br.resource_id WHERE br.bundle_id=$1 AND r.active=TRUE ORDER BY br.position`,[bundleDbId])).rows.map(row=>row.stable_key)}
 resourceKeys=[...new Set(resourceKeys)];if(!arrangementName||!resourceKeys.length)throw new Error('ALLOCATION_REQUIRED');const resources=await client.query(`SELECT id,stable_key,display_name,sleeping_capacity,availability_property_id FROM accommodation_resources WHERE stable_key=ANY($1::text[]) AND active=TRUE`,[resourceKeys]);if(resources.rowCount!==resourceKeys.length)throw new Error('INVALID_ALLOCATION_RESOURCE');const nominal=resources.rows.reduce((sum,row)=>sum+Number(row.sleeping_capacity),0);const approved=Number(input.approvedSleepingCapacity??nominal);const alternative=clean(input.alternativeSleepingNotes,2000)||null;if(!Number.isInteger(approved)||approved<0||approved>nominal&& !alternative)throw new Error('ALTERNATIVE_SLEEPING_NOTES_REQUIRED');if(approved<input.requiredAdults&&!alternative)throw new Error('ALLOCATION_CAPACITY_REVIEW_REQUIRED');
 const allocation=await client.query(`INSERT INTO booking_offer_allocations(booking_offer_id,bundle_id,arrangement_name,approved_sleeping_capacity,alternative_sleeping_notes,explanatory_notes) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[input.offerId,bundleDbId,arrangementName,approved,alternative,clean(input.explanatoryNotes,3000)||null]);for(const [position,resourceKey] of resourceKeys.entries()){const resource=resources.rows.find(row=>row.stable_key===resourceKey);await client.query(`INSERT INTO booking_offer_allocation_resources(allocation_id,resource_id,resource_key,resource_name,sleeping_capacity,availability_property_id,position) VALUES($1,$2,$3,$4,$5,$6,$7)`,[allocation.rows[0].id,resource.id,resource.stable_key,resource.display_name,resource.sleeping_capacity,resource.availability_property_id,position])}
}
export async function getOfferAllocation(offerId:string,database:pg.Pool|pg.PoolClient=getPool()):Promise<OfferAllocation|null>{const row=await database.query(`SELECT a.arrangement_name AS "arrangementName",a.approved_sleeping_capacity AS "approvedSleepingCapacity",a.alternative_sleeping_notes AS "alternativeSleepingNotes",a.explanatory_notes AS "explanatoryNotes",COALESCE(jsonb_agg(jsonb_build_object('key',r.resource_key,'name',r.resource_name,'sleepingCapacity',r.sleeping_capacity,'availabilityPropertyId',r.availability_property_id) ORDER BY r.position) FILTER(WHERE r.resource_id IS NOT NULL),'[]') AS resources FROM booking_offer_allocations a LEFT JOIN booking_offer_allocation_resources r ON r.allocation_id=a.id WHERE a.booking_offer_id=$1 GROUP BY a.id`,[offerId]);return row.rowCount?{...row.rows[0],approvedSleepingCapacity:Number(row.rows[0].approvedSleepingCapacity)}:null}
export async function countCompetingActiveOffers(offerId:string,database:pg.Pool|pg.PoolClient=getPool()):Promise<number>{const result=await database.query(`SELECT COUNT(DISTINCT competing.id)::int AS count FROM booking_offers current_offer JOIN provisional_bookings current_booking ON current_booking.id=current_offer.provisional_booking_id JOIN booking_offer_allocations current_allocation ON current_allocation.booking_offer_id=current_offer.id JOIN booking_offer_allocation_resources current_resource ON current_resource.allocation_id=current_allocation.id JOIN booking_offer_allocation_resources competing_resource ON competing_resource.resource_id=current_resource.resource_id JOIN booking_offer_allocations competing_allocation ON competing_allocation.id=competing_resource.allocation_id JOIN booking_offers competing ON competing.id=competing_allocation.booking_offer_id JOIN provisional_bookings competing_booking ON competing_booking.id=competing.provisional_booking_id WHERE current_offer.id=$1 AND competing.id<>current_offer.id AND competing.customer_status='active' AND competing_booking.arrival<current_booking.departure AND competing_booking.departure>current_booking.arrival`,[offerId]);return Number(result.rows[0]?.count||0)}
export async function assertAllocationAvailable(client:pg.PoolClient,offerId:string,arrival:string,departure:string,bookingId:string){const resources=await client.query(`SELECT r.resource_id,r.resource_key FROM booking_offer_allocation_resources r JOIN booking_offer_allocations a ON a.id=r.allocation_id WHERE a.booking_offer_id=$1 ORDER BY r.resource_id FOR SHARE OF r`,[offerId]);for(const resource of resources.rows)await client.query('SELECT pg_advisory_xact_lock($1)',[resource.resource_id]);const conflict=await client.query(`SELECT rr.resource_id FROM accommodation_resource_reservations rr WHERE rr.resource_id=ANY($1::bigint[]) AND rr.provisional_booking_id<>$2 AND rr.status='active' AND rr.starts_on<$4::date AND rr.ends_on>$3::date LIMIT 1`,[resources.rows.map(row=>row.resource_id),bookingId,arrival,departure]);if(conflict.rowCount)throw new Error('ALLOCATION_UNAVAILABLE');return resources.rows}
export async function reserveOfferAllocation(client:pg.PoolClient,input:{offerId:string;bookingId:string;arrival:string;departure:string}){const resources=await assertAllocationAvailable(client,input.offerId,input.arrival,input.departure,input.bookingId);for(const resource of resources)await client.query(`INSERT INTO accommodation_resource_reservations(resource_id,provisional_booking_id,booking_offer_id,starts_on,ends_on) VALUES($1,$2,$3,$4,$5) ON CONFLICT(resource_id,booking_offer_id) DO NOTHING`,[resource.resource_id,input.bookingId,input.offerId,input.arrival,input.departure])}
export async function releaseBookingResourceReservations(client:pg.PoolClient,bookingId:string,reason:string){return client.query(`UPDATE accommodation_resource_reservations SET status='released',released_at=NOW(),release_reason=$2 WHERE provisional_booking_id=$1 AND status='active'`,[bookingId,reason])}
