import type pg from 'pg';import {getPool} from '../booking/db.ts';
import {getProperty} from '../booking/config.ts';
export type AccommodationResource={id:string;stableKey:string;displayName:string;sleepingCapacity:number;availabilityPropertyId:string|null;practicalNotes:string|null;active:boolean};
export type AccommodationBundle={id:string;stableKey:string;displayName:string;practicalNotes:string|null;standardArrangement:boolean;active:boolean;sleepingCapacity:number;resources:AccommodationResource[];propertyIds:string[]};
const clean=(value:unknown,max:number)=>String(value??'').trim().slice(0,max);const key=(value:unknown)=>clean(value,100);
const validKey=(value:string)=>/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value);
export async function listAccommodationModel(database:pg.Pool|pg.PoolClient=getPool()):Promise<{resources:AccommodationResource[];bundles:AccommodationBundle[]}>{
 const resources=(await database.query(`SELECT id::text,stable_key AS "stableKey",display_name AS "displayName",sleeping_capacity AS "sleepingCapacity",availability_property_id AS "availabilityPropertyId",practical_notes AS "practicalNotes",active FROM accommodation_resources ORDER BY stable_key`)).rows.map(row=>({...row,sleepingCapacity:Number(row.sleepingCapacity)}));
 const bundles=(await database.query(`SELECT b.public_id::text AS id,b.stable_key AS "stableKey",b.display_name AS "displayName",b.practical_notes AS "practicalNotes",b.standard_arrangement AS "standardArrangement",b.active,COALESCE(SUM(r.sleeping_capacity),0)::int AS "sleepingCapacity",COALESCE(array_agg(r.stable_key ORDER BY br.position) FILTER(WHERE r.id IS NOT NULL),'{}') AS resource_keys,COALESCE(array_agg(DISTINCT pb.property_id) FILTER(WHERE pb.property_id IS NOT NULL),'{}') AS property_ids FROM accommodation_bundles b LEFT JOIN accommodation_bundle_resources br ON br.bundle_id=b.id LEFT JOIN accommodation_resources r ON r.id=br.resource_id LEFT JOIN accommodation_property_bundles pb ON pb.bundle_id=b.id GROUP BY b.id ORDER BY b.standard_arrangement DESC,b.stable_key`)).rows;
 return {resources,bundles:bundles.map(row=>({id:row.id,stableKey:row.stableKey,displayName:row.displayName,practicalNotes:row.practicalNotes,standardArrangement:row.standardArrangement,active:row.active,sleepingCapacity:Number(row.sleepingCapacity),resources:row.resource_keys.map((resourceKey:string)=>resources.find(item=>item.stableKey===resourceKey)!),propertyIds:row.property_ids}))};
}
export async function saveAccommodationResource(input:{stableKey:unknown;displayName:unknown;sleepingCapacity:unknown;availabilityPropertyId?:unknown;practicalNotes?:unknown;adminUserId:string},database:pg.Pool=getPool()){
 const stableKey=key(input.stableKey),displayName=clean(input.displayName,160),capacity=Number(input.sleepingCapacity),availability=clean(input.availabilityPropertyId,100)||null,notes=clean(input.practicalNotes,2000)||null;if(!validKey(stableKey)||!displayName||!Number.isInteger(capacity)||capacity<0||(availability&&!getProperty(availability)))throw new Error('INVALID_RESOURCE');
 const client=await database.connect();try{await client.query('BEGIN');const saved=await client.query(`UPDATE accommodation_resources SET display_name=$2,sleeping_capacity=$3,availability_property_id=$4,practical_notes=$5,updated_at=NOW() WHERE stable_key=$1 RETURNING id`,[stableKey,displayName,capacity,availability,notes]);if(!saved.rowCount)throw new Error('RESOURCE_NOT_FOUND');await client.query(`INSERT INTO accommodation_resource_events(admin_user_id,action,resource_id,details) VALUES($1,'resource_updated',$2,$3::jsonb)`,[input.adminUserId,saved.rows[0].id,JSON.stringify({stableKey,displayName,capacity,availability})]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}
}
export async function createAccommodationBundle(input:{stableKey:unknown;displayName:unknown;practicalNotes?:unknown;resourceKeys:unknown[];adminUserId:string},database:pg.Pool=getPool()){
 const stableKey=key(input.stableKey),displayName=clean(input.displayName,160),notes=clean(input.practicalNotes,2000)||null,resourceKeys=[...new Set(input.resourceKeys.map(key).filter(Boolean))];if(!validKey(stableKey)||!displayName||!resourceKeys.length)throw new Error('INVALID_BUNDLE');
 const client=await database.connect();try{await client.query('BEGIN');const selected=await client.query(`SELECT id,stable_key FROM accommodation_resources WHERE stable_key=ANY($1::text[]) AND active=TRUE`,[resourceKeys]);if(selected.rowCount!==resourceKeys.length)throw new Error('INVALID_BUNDLE_RESOURCE');const created=await client.query(`INSERT INTO accommodation_bundles(stable_key,display_name,practical_notes,created_by) VALUES($1,$2,$3,$4) RETURNING id,public_id::text AS id_public`,[stableKey,displayName,notes,input.adminUserId]);for(const [position,resourceKey] of resourceKeys.entries()){const resource=selected.rows.find(row=>row.stable_key===resourceKey);await client.query(`INSERT INTO accommodation_bundle_resources(bundle_id,resource_id,position) VALUES($1,$2,$3)`,[created.rows[0].id,resource.id,position])}await client.query(`INSERT INTO accommodation_resource_events(admin_user_id,action,bundle_id,details) VALUES($1,'bundle_created',$2,$3::jsonb)`,[input.adminUserId,created.rows[0].id,JSON.stringify({stableKey,displayName,resourceKeys})]);await client.query('COMMIT');return created.rows[0].id_public as string;}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}
}
export async function updateAccommodationBundle(input:{id:unknown;displayName:unknown;practicalNotes?:unknown;resourceKeys:unknown[];adminUserId:string},database:pg.Pool=getPool()){
 const id=clean(input.id,36),displayName=clean(input.displayName,160),notes=clean(input.practicalNotes,2000)||null,resourceKeys=[...new Set(input.resourceKeys.map(key).filter(Boolean))];if(!/^[0-9a-f-]{36}$/i.test(id)||!displayName||!resourceKeys.length)throw new Error('INVALID_BUNDLE');
 const client=await database.connect();try{await client.query('BEGIN');const bundle=await client.query(`SELECT id,stable_key FROM accommodation_bundles WHERE public_id=$1::uuid AND standard_arrangement=FALSE AND active=TRUE FOR UPDATE`,[id]);if(!bundle.rowCount)throw new Error('BUNDLE_NOT_EDITABLE');const selected=await client.query(`SELECT id,stable_key FROM accommodation_resources WHERE stable_key=ANY($1::text[]) AND active=TRUE`,[resourceKeys]);if(selected.rowCount!==resourceKeys.length)throw new Error('INVALID_BUNDLE_RESOURCE');await client.query(`UPDATE accommodation_bundles SET display_name=$2,practical_notes=$3,updated_at=NOW() WHERE id=$1`,[bundle.rows[0].id,displayName,notes]);await client.query(`DELETE FROM accommodation_bundle_resources WHERE bundle_id=$1`,[bundle.rows[0].id]);for(const [position,resourceKey] of resourceKeys.entries()){const resource=selected.rows.find(row=>row.stable_key===resourceKey);await client.query(`INSERT INTO accommodation_bundle_resources(bundle_id,resource_id,position) VALUES($1,$2,$3)`,[bundle.rows[0].id,resource.id,position])}await client.query(`INSERT INTO accommodation_resource_events(admin_user_id,action,bundle_id,details) VALUES($1,'bundle_updated',$2,$3::jsonb)`,[input.adminUserId,bundle.rows[0].id,JSON.stringify({stableKey:bundle.rows[0].stable_key,displayName,resourceKeys})]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}
}
export async function listAccommodationEvents(database:pg.Pool|pg.PoolClient=getPool()){return (await database.query(`SELECT e.id::text,e.action,e.details,e.created_at AS "createdAt",u.display_name AS "adminName" FROM accommodation_resource_events e LEFT JOIN admin_users u ON u.id=e.admin_user_id ORDER BY e.created_at DESC,e.id DESC LIMIT 100`)).rows}
