import assert from 'node:assert/strict';import crypto from 'node:crypto';import {readdir,readFile} from 'node:fs/promises';import test from 'node:test';import pg from 'pg';
const {Pool}=pg;const databaseUrl=process.env.TEST_DATABASE_URL||process.env.DATABASE_URL;const quote=(value:string)=>`"${value.replaceAll('"','""')}"`;
test('resource migration resolves standard bundles and distinguishes Cottage dependency',async()=>{assert.ok(databaseUrl,'Set TEST_DATABASE_URL or DATABASE_URL.');const schema=`accommodation_resources_${process.pid}_${crypto.randomBytes(5).toString('hex')}`;const control=new Pool({connectionString:databaseUrl,max:1});const url=new URL(databaseUrl!);url.searchParams.set('options',`-c search_path=${schema},public`);const db=new Pool({connectionString:url.toString(),max:1});
 try{await control.query(`CREATE SCHEMA ${quote(schema)}`);const directory=new URL('../../db/',import.meta.url);for(const file of (await readdir(directory)).filter(name=>name.endsWith('.sql')).sort())await db.query(await readFile(new URL(file,directory),'utf8'));
 const rows=(await db.query(`SELECT pb.property_id,b.stable_key,COALESCE(SUM(r.sleeping_capacity),0)::int AS capacity,array_agg(r.stable_key ORDER BY br.position) AS resources,array_agg(DISTINCT r.availability_property_id) FILTER(WHERE r.availability_property_id IS NOT NULL) AS calendars FROM accommodation_property_bundles pb JOIN accommodation_bundles b ON b.id=pb.bundle_id LEFT JOIN accommodation_bundle_resources br ON br.bundle_id=b.id LEFT JOIN accommodation_resources r ON r.id=br.resource_id GROUP BY pb.property_id,b.stable_key ORDER BY pb.property_id`)).rows;
 const main=rows.find(row=>row.property_id==='main-house'),max=rows.find(row=>row.property_id==='whole-property'),cottage=rows.find(row=>row.property_id==='cottage');assert.equal(main.capacity,8);assert.deepEqual(main.resources,['olrig-bank-core']);assert.equal(max.capacity,12);assert.ok(max.calendars.includes('main-house')&&max.calendars.includes('cottage'));assert.equal(cottage.capacity,4);assert.ok(cottage.resources.includes('cottage-independent-living'));
 await db.query(`UPDATE accommodation_resources SET display_name='Renamed rear room' WHERE stable_key='rear-bedroom-5'`);assert.equal((await db.query(`SELECT stable_key FROM accommodation_resources WHERE display_name='Renamed rear room'`)).rows[0].stable_key,'rear-bedroom-5');
 await assert.rejects(db.query(`INSERT INTO accommodation_bundles(stable_key,display_name) VALUES('Invalid Key','Invalid')`),/accommodation_bundles_stable_key_check/);
 }finally{await db.end();await control.query(`DROP SCHEMA IF EXISTS ${quote(schema)} CASCADE`);await control.end()}});
