import assert from 'node:assert/strict';import crypto from 'node:crypto';import {readdir,readFile} from 'node:fs/promises';import test from 'node:test';import pg from 'pg';import {releaseBookingResourceReservations,reserveOfferAllocation,snapshotOfferAllocation} from '../../src/lib/accommodation/allocation.ts';
const {Pool}=pg;const databaseUrl=process.env.TEST_DATABASE_URL||process.env.DATABASE_URL;const quote=(value:string)=>`"${value.replaceAll('"','""')}"`;
test('concurrent allocations cannot reserve the same Cottage-dependent resource',async()=>{assert.ok(databaseUrl,'Set TEST_DATABASE_URL or DATABASE_URL.');const schema=`offer_allocation_${process.pid}_${crypto.randomBytes(5).toString('hex')}`;const control=new Pool({connectionString:databaseUrl,max:1});const url=new URL(databaseUrl!);url.searchParams.set('options',`-c search_path=${schema},public`);const db=new Pool({connectionString:url.toString(),max:4});
 try{await control.query(`CREATE SCHEMA ${quote(schema)}`);const directory=new URL('../../db/',import.meta.url);for(const file of (await readdir(directory)).filter(name=>name.endsWith('.sql')).sort())await db.query(await readFile(new URL(file,directory),'utf8'));
 const bookings=(await db.query(`INSERT INTO provisional_bookings(property_id,arrival,departure,adults,children,infants,pets,guest_name,guest_email,originated_as_bespoke) VALUES('cottage',CURRENT_DATE+30,CURRENT_DATE+33,2,0,0,0,'One','one@example.invalid',TRUE),('whole-property',CURRENT_DATE+31,CURRENT_DATE+34,2,0,0,0,'Two','two@example.invalid',TRUE) RETURNING id,arrival::text,departure::text`)).rows;
 const offers:Array<{id:string}>=[];for(const booking of bookings)offers.push((await db.query(`INSERT INTO booking_offers(provisional_booking_id,currency,line_items,total_pence,recipient_email,subject,delivery_status) VALUES($1,'GBP','[]',10000,'x@example.invalid','Offer','not_requested') RETURNING id::text`,[booking.id])).rows[0]);
 for(let index=0;index<offers.length;index++){const client=await db.connect();try{await client.query('BEGIN');await snapshotOfferAllocation(client,{offerId:offers[index].id,resourceKeys:['rear-bedroom-5'],arrangementName:`Arrangement ${index+1}`,approvedSleepingCapacity:2,requiredAdults:2});await client.query('COMMIT')}finally{client.release()}}
 const attempts=await Promise.allSettled(bookings.map(async(booking,index)=>{const client=await db.connect();try{await client.query('BEGIN');await reserveOfferAllocation(client,{offerId:offers[index].id,bookingId:String(booking.id),arrival:booking.arrival,departure:booking.departure});await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}}));assert.equal(attempts.filter(result=>result.status==='fulfilled').length,1);assert.equal((await db.query(`SELECT COUNT(*)::int AS count FROM accommodation_resource_reservations WHERE status='active'`)).rows[0].count,1);
 const winner=bookings[attempts.findIndex(result=>result.status==='fulfilled')];const client=await db.connect();try{await client.query('BEGIN');await releaseBookingResourceReservations(client,String(winner.id),'booking_cancelled');await client.query('COMMIT')}finally{client.release()}assert.equal((await db.query(`SELECT status FROM accommodation_resource_reservations`)).rows[0].status,'released');
 }finally{await db.end();await control.query(`DROP SCHEMA IF EXISTS ${quote(schema)} CASCADE`);await control.end()}});
